# 迁移注册表
# 先挂载相应文件，然后填写此配置文件
# 挂载相应文件的参考：
# 注册表配置单元                 支持文件
# HKEY_CURRENT_CONFIG           System、System.alt、System.log、System.sav
# HKEY_CURRENT_USER             Ntuser.dat、Ntuser.dat.log
# HKEY_LOCAL_MACHINE\SAM        Sam、Sam.log、Sam.sav
# HKEY_LOCAL_MACHINE\Security	Security、Security.log、Security.sav
# HKEY_LOCAL_MACHINE\Software	Software、Software.log、Software.sav
# HKEY_LOCAL_MACHINE\System     System、System.alt、System.log、System.sav
# HKEY_USERS\.DEFAULT           Default、Default.log、Default.sav
# 支持glob​ 风格
[[reg]]
path_key_src = 'HKEY_CURRENT_USER\AAA'
path_key_dst = 'HKEY_CURRENT_USER\BBB'
[allow]
[[path_key_value]]
# 绝对路径，而不是相对于 path_key_src
path_key = 'HKEY_CURRENT_USER\AAA'
# 假设与 path_key 匹配的路径是 A
# 那么 value 相对于 A 里面的值(注册表值)
# 如果 A 里面的值与 value 匹配，则产生相应效果(allow|deny)
value = 'BBB'
[deny]
[[path_key_value]]
# 绝对路径，而不是相对于 path_key_src
path_key = 'HKEY_CURRENT_USER\AAA'
# 假设与 path_key 匹配的路径是 A
# 那么 value 相对于 A 里面的值(注册表值)
# 如果 A 里面的值与 value 匹配，则产生相应效果(allow|deny)
value = 'BBB'

# 迁移文件
# 不支持Win环境变量
# 不支持通配符，它会迁移 “提供的路径” 里面的任何东西，排除项除外
# “path/” 与 “path” 的区别是，一个会迁移 “path” 文件夹里面的任何东西但不包括 “path” 文件夹本身，一个会迁移 “path” 文件夹
# overlap 覆盖目标文件
# no 排除项，以源路径为基准
# 排除项中的项目应确保存在于源路径中，否则它将不起作用；换句话说，排除项不会应用于其他 [[file]]
# 排除项语法支持：
# no=[
# '*.pyc',
# 'tmp*'
# ]
# 这将会迁移除 .pyc 文件和以 tmp 打头的文件或目录以外的所有条目。
[[file]]
path_src='C:\Windows\System32\config'
path_dst='dst'
overlap=true
no=[
    'B*'
]
